import { StyleSheet } from 'react-native';
import { scale, moderateScale, verticalScale } from 'react-native-size-matters';

const getStyles = (colors) => StyleSheet.create({
    scrollContainer: {
        flexGrow: 1,
        backgroundColor: colors.white,
    },
    container: {
        flex: 1,
        paddingHorizontal: scale(24),
        justifyContent: 'center',
        paddingBottom: verticalScale(20),
    },
    header: {
        alignItems: 'center',
        marginBottom: scale(10),
        marginTop: verticalScale(6),
    },
    logoContainer: {
        width: scale(80),
        height: scale(80),
        borderRadius: scale(40),
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: scale(10),
    },
    title: {
        fontSize: moderateScale(28),
        fontWeight: '700',
        color: colors.primary,
        marginBottom: scale(8),
        textAlign: 'center',
    },
    subtitle: {
        fontSize: moderateScale(15),
        color: colors.grey,
        textAlign: 'center',
        lineHeight: moderateScale(22),
    },
    inputGroup: {
        marginBottom: scale(8),
    },
    rowGroup: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: scale(10),
    },
    halfInputGroup: {
        flex: 1,
    },
    label: {
        fontSize: moderateScale(12),
        fontWeight: '700',
        color: colors.primary,
        marginBottom: scale(8),
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        // backgroundColor: colors.gray100 || colors.lightGrey,
        borderRadius: scale(8),
        paddingHorizontal: scale(16),
        height: scale(48),
        borderWidth: 1,
        borderColor: colors.gray200 || colors.lightGrey,
    },
    inputWrapperActive: {
        borderColor: colors.primary,
        backgroundColor: '#fff',
    },
    input: {
        flex: 1,
        marginLeft: scale(8),
        fontSize: moderateScale(16),
        color: colors.black,
    },
    phoneInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    phoneFlagButton: {
        backgroundColor: colors.white,
        paddingHorizontal: scale(6),
        paddingVertical: verticalScale(10),
    },
    phoneTextContainer: {
        flex: 1,
        borderWidth: 2,
        borderColor: colors?.gray200,
        borderRadius: scale(8),
        height: scale(48),
        justifyContent: 'center',
        backgroundColor: colors.white,
        paddingHorizontal: scale(12),
    },
    phoneTextInput: {
        fontSize: moderateScale(16),
        color: colors.black,
    },
    roleSection: {
        marginTop: scale(5),
        marginBottom: scale(18),
    },
    roleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: scale(8),
    },
    roleOption: {
        width: scale(93),
        height: scale(93),
        borderRadius: scale(8),
        borderWidth: 1,
        borderColor: colors.gray200 || '#e5e7eb',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
        backgroundColor: colors.white,
    },
    roleOptionSelected: {
        borderColor: colors.primary,
        borderWidth: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 3,
    },
    roleIconBox: {
        width: scale(44),
        height: scale(44),
        borderRadius: scale(10),
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: scale(8),
        backgroundColor: colors.gray50 || '#fafafa',
    },
    roleIconBoxSelected: {
        borderWidth: 1,
        borderColor: colors.primary,
    },
    roleText: {
        fontSize: moderateScale(13),
        color: colors.black,
        marginTop: scale(4),
        fontWeight: '600',
    },
    signUpButton: {
        height: scale(48),
        borderRadius: scale(8),
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: scale(22),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.18,
        shadowRadius: 18,
        elevation: 6,
    },
    buttonText: {
        fontSize: moderateScale(16),
        fontWeight: '700',
        color: colors.white,
        letterSpacing: 1,
    },
    bottomRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: scale(18),
    },
    bottomText: {
        fontSize: moderateScale(14),
        color: colors.grey,
    },
    bottomLink: {
        fontSize: moderateScale(14),
        color: colors.primary,
        fontWeight: '600',
        marginLeft: scale(4),
    },
    errorText: {
        color: colors.red || 'red',
        fontSize: moderateScale(12),
        marginTop: moderateScale(6),
    },
    header1: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: moderateScale(16),
        paddingTop: moderateScale(50),
        paddingBottom: moderateScale(30),
        backgroundColor: colors.primary,
    },
    headerRight: {
        width: moderateScale(40),
    },
    headerTitle: {
        fontSize: moderateScale(18),
        fontWeight: '700',
        color: colors.white,
    },
});

export default getStyles;